# This is a TOML document

[collections.messages]
[[collections.messages.indexes]]
fields = [["datetime"]]

[collections.users]

[collections.chat]
[[collections.chat.indexes]]
fields = [["datetime"]]

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"
